import { Github, Linkedin, Mail } from "lucide-react";
import { PortfolioData } from "@/types/portfolio";

export const PORTFOLIO_DATA: PortfolioData = {
  navigation: [
    { label: "Profil", href: "#about" },
    { label: "Pengalaman", href: "#experience" },
    { label: "Karya Terpilih", href: "#projects" },
    { label: "Pendidikan", href: "#education" },
    { label: "Pencapaian", href: "#achievements" },
    { label: "Sertifikasi", href: "#certifications" },
    { label: "Kontak", href: "#contact" },
  ],
  socials: [
    {
      icon: Github,
      href: "https://github.com/Alfian57",
      label: "GitHub",
    },
    {
      icon: Linkedin,
      href: "https://www.linkedin.com/in/alfian-gading-saputra/",
      label: "LinkedIn",
    },
    {
      icon: Mail,
      href: "mailto:alfiangadingsaputra@gmail.com",
      label: "Email",
    },
  ],
  hero: {
    greeting: "Halo!",
    name: "Alfian Gading Saputra",
    tagline: "Fullstack Developer",
    description:
      "Saya membantu membangun aplikasi web dengan fondasi backend yang rapi, alur data yang jelas, dan antarmuka yang mudah digunakan. Stack utama saya meliputi Laravel, Go, SQL, Next.js, TypeScript, Docker, Linux, dan Tailwind CSS.",
    cta: {
      primary: "Lihat Studi Kasus",
      secondary: "Diskusi Peluang",
    },
  },
  about: {
    title: "Profil",
    description: [
      "Saya adalah Fullstack Developer dengan fokus kuat pada backend, desain API, database, dan integrasi antarmuka. Saya terbiasa bekerja dengan Laravel, PHP, SQL, Linux, serta terus memperkuat Go, Next.js, dan TypeScript untuk membangun sistem web yang lebih modern.",
      "Dalam pekerjaan, saya berusaha membuat alur data mudah dipahami, struktur kode tidak cepat rapuh, dan performa diperhatikan sejak awal. Saya nyaman bergerak dari perancangan skema database, pembuatan endpoint, penelusuran bug, sampai penyusunan UI yang rapi.",
      "Saya menyusun portofolio ini agar perekrut dan tim teknis bisa cepat melihat fokus keahlian, pengalaman industri, pencapaian kompetitif, dan bukti kerja yang relevan.",
    ],
    skills: [
      "Golang",
      "Laravel",
      "Next.js",
      "TypeScript",
      "SQL",
      "Tailwind CSS",
      "Node.js",
      "Docker",
      "Git",
      "Linux",
    ],
  },
  experiences: [
    {
      id: "exp-1",
      title: "Asisten Dosen",
      company: "Universitas Teknologi Yogyakarta",
      location: "Daerah Istimewa Yogyakarta, Indonesia",
      period: "September 2025 - Sekarang",
      description: [
        "Membimbing 80+ mahasiswa dalam mata kuliah Jaringan Komputer & Komunikasi Data, termasuk simulasi jaringan dan pemecahan masalah menggunakan Cisco Packet Tracer.",
        "Mengajar logika pemrograman Python untuk mata kuliah Algoritma & Pemrograman Dasar, berfokus pada alur kontrol dan struktur data agar mahasiswa mampu menulis kode yang lebih terstruktur.",
      ],
      technologies: ["Cisco Packet Tracer", "Python"],
      type: "Contract",
      images: [],
    },
    {
      id: "exp-2",
      title: "Backend Developer",
      company: "UTY Software House",
      location: "Daerah Istimewa Yogyakarta, Indonesia",
      period: "Juli 2025 - Sekarang",
      description: [
        "Merancang layanan backend yang skalabel menggunakan Laravel dengan fokus pada struktur kode yang rapi dan desain API yang aman.",
        "Menyusun skema database yang efisien serta mengoptimalkan query SQL untuk menangani relasi data yang kompleks.",
        "Berkolaborasi dengan tim frontend untuk merumuskan spesifikasi API dan memastikan aliran data berjalan lancar di seluruh aplikasi.",
      ],
      technologies: ["PHP", "Laravel"],
      type: "Contract",
      images: ["/experience/USH-1.jpeg", "/experience/USH-2.jpeg"],
    },
    {
      id: "exp-3",
      title: "Fullstack Developer",
      company: "Seven Inc Jogja",
      location: "Daerah Istimewa Yogyakarta, Indonesia",
      period: "Juni 2023 - September 2023",
      description: [
        "Membangun dan menyesuaikan solusi content management berbasis WordPress dan Laravel agar sesuai dengan kebutuhan spesifik klien.",
        "Mengelola environment server berbasis Linux, termasuk deployment dasar dan konfigurasi untuk menjaga stabilitas layanan.",
        "Mengoptimalkan query database dan skrip backend untuk meningkatkan kecepatan muat halaman serta performa sistem secara keseluruhan.",
      ],
      technologies: ["PHP", "Laravel", "WordPress", "Linux"],
      type: "Internship",
      images: ["/experience/Seven-Inc-1.jpg", "/experience/Seven-Inc-2.jpg"],
    },
    {
      id: "exp-4",
      title: "Fullstack Developer",
      company: "PT. Integra Inovasi Indonesia",
      location: "Daerah Istimewa Yogyakarta, Indonesia",
      period: "Juni 2022 - Desember 2022",
      description: [
        "Mengembangkan dan memelihara aplikasi web berbasis Laravel dengan integrasi yang rapi antara logika backend dan tampilan frontend.",
        "Berkolaborasi dalam pengembangan aplikasi mobile menggunakan Java Android, khususnya pada konsumsi RESTful API dan sinkronisasi data.",
        "Berperan dalam perbaikan bug dan penyempurnaan fitur untuk meningkatkan stabilitas aplikasi serta pengalaman pengguna.",
      ],
      technologies: ["PHP", "Laravel", "Java", "Android"],
      type: "Internship",
      images: ["/experience/Integra-1.jpg"],
    },
  ],
  projects: [
    {
      id: "proj-1",
      title: "SIM PKM - Website PKM Internal UTY",
      description:
        "Mengembangkan sistem manajemen dan penilaian proposal internal berbasis Laravel menggunakan arsitektur monorepo untuk program PKM UTY 2026. Sistem ini mendukung otorisasi tiga peran, yaitu mahasiswa, admin, dan reviewer, serta logika penilaian yang terintegrasi untuk mempercepat siklus pengajuan proposal.",
      image: "/editorial/project-sim-pkm.png",
      technologies: ["Laravel", "PHP"],
      tags: ["Pengembangan Web", "Backend"],
      role: "Backend Developer",
      context: "Program PKM Universitas Teknologi Yogyakarta, 2026.",
      highlights: [
        "Merancang sistem manajemen proposal dengan kontrol akses berbasis peran (RBAC).",
        "Membangun logika penilaian otomatis untuk mengoptimalkan siklus tinjauan proposal.",
        "Mengimplementasikan arsitektur monorepo agar pengembangan dan pemeliharaan lebih terstruktur.",
      ],
      outcome:
        "Sistem yang efisien dalam mengelola dan menilai proposal PKM UTY dengan proses yang terstruktur dan aman.",
      images: [],
      featured: true,
    },
    {
      id: "proj-2",
      title: "Panca Trivia - Website Edukasi Pancasila",
      description:
        "Membangun aplikasi web edukatif berbasis Laravel dengan konsep gamification untuk mendukung pembelajaran nilai-nilai Pancasila. Fitur kuis interaktif dan sistem level dirancang agar proses belajar lebih terarah, terukur, dan menarik.",
      image: "/editorial/project-panca-trivia-mockup.png",
      technologies: ["Laravel", "PHP", "JavaScript", "Gamification", "Desain Database"],
      tags: ["Edukasi", "Pengembangan Web", "Fullstack"],
      role: "Fullstack Developer",
      context: "Proyek pengembangan aplikasi edukatif untuk pembelajaran Pancasila.",
      highlights: [
        "Merancang sistem gamification dengan fitur poin, badge, dan leaderboard.",
        "Membangun fitur kuis interaktif dengan umpan balik real-time.",
        "Mengimplementasikan sistem level progresif untuk menjaga keterlibatan pengguna.",
      ],
      outcome:
        "Platform edukatif yang interaktif untuk membantu pembelajaran nilai-nilai Pancasila melalui gamification.",
      images: [],
      featured: true,
    },
  ],
  education: [
    {
      id: "edu-1",
      degree: "Sarjana Ilmu Komputer",
      institution: "Universitas Teknologi Yogyakarta",
      location: "Daerah Istimewa Yogyakarta, Indonesia",
      period: "2023 - Sekarang",
      description:
        "Sedang memperdalam pengetahuan di bidang struktur data, algoritma, dan arsitektur sistem. Secara aktif menjembatani teori akademik dengan standar industri melalui penerapan prinsip rekayasa perangkat lunak di proyek nyata bersama UTY Software House.",
    },
    {
      id: "edu-2",
      degree: "Rekayasa Perangkat Lunak",
      institution: "SMK Negeri 1 Bantul",
      location: "Daerah Istimewa Yogyakarta, Indonesia",
      period: "2020 - 2023",
      description:
        "Membangun fondasi kuat pada pengembangan web, manajemen database, dan pemrograman berorientasi objek. Mendapat pengalaman implementasi fullstack melalui pembelajaran vokasi dan magang industri.",
    },
  ],
  achievements: [
    {
      id: "ach-1",
      title: "Juara 2 LKS ITSSB Tingkat Provinsi DIY",
      issuer: "Disdikpora DIY",
      date: "Mei 2022",
      description:
        "Meraih juara 2 pada kompetisi vokasi bergengsi IT Software Solutions for Business tingkat Provinsi DIY.",
      detailedDescription:
        "Mengembangkan rangkaian perangkat lunak dalam batas waktu yang ketat. Proyek ini mencakup aplikasi desktop Point of Sales berbasis C# .NET untuk manajemen ritel serta aplikasi Cloud Storage berbasis Android menggunakan Java, dengan fokus pada pengelolaan file dan sinkronisasi API.",
      tags: ["C# .NET", "Java Android", "Aplikasi Desktop", "Integrasi Sistem"],
      images: ["/achivement/LKS-1.jpeg", "/achivement/LKS-2.jpeg", "/achivement/LKS-3.jpeg"],
      link: "/achivement/LKS-Cert.jpg",
    },
    {
      id: "ach-2",
      title: "Juara 3 LKS ITSSB Tingkat Nasional",
      issuer: "Kementerian Pendidikan dan Kebudayaan Republik Indonesia",
      date: "Oktober 2022",
      description:
        "Meraih peringkat 3 tingkat nasional setelah bersaing dengan talenta terbaik dari 34 provinsi Indonesia di bidang IT Software Solutions for Business.",
      detailedDescription:
        "Membangun solusi bisnis terintegrasi yang menggabungkan modul desktop, web, dan mobile. Kompetisi ini menunjukkan kemampuan menggunakan C# .NET dan Java untuk menyelesaikan logika bisnis yang kompleks di bawah tekanan waktu.",
      tags: ["Penghargaan Nasional", "C# .NET", "Java", "Rekayasa Fullstack"],
      images: ["/achivement/LKSN-1.jpeg", "/achivement/LKSN-2.jpeg", "/achivement/LKSN-3.jpeg"],
      link: "/achivement/LKSN-Cert.jpg",
    },
    {
      id: "ach-3",
      title: "Penerima Pendanaan PKM-KC (SINDIKAT)",
      issuer: "Kemdikbudristek",
      date: "Agustus 2024",
      description:
        "Menerima pendanaan hibah riset untuk proyek PKM-KC 'SINDIKAT', sebuah karya inovatif yang memanfaatkan Deep Learning untuk kebutuhan keamanan.",
      detailedDescription:
        "Berperan sebagai Lead Backend Developer untuk 'SINDIKAT: Sistem Multi Device Pendeteksi Tindakan Kriminal Menggunakan Deep Learning'. Bertanggung jawab merancang RESTful API yang memproses peringatan real-time dari model AI serta mengelola aliran data antara beberapa endpoint perangkat dan dashboard pusat.",
      tags: ["PKM-KC", "Integrasi AI", "Arsitektur Backend", "Deep Learning"],
      images: [],
      link: "/achivement/PKM-Cert.jpg",
    },
  ],
  certifications: [
    {
      id: "cert-1",
      title: "Junior Web Developer",
      issuer: "Badan Nasional Sertifikasi Profesi (BNSP)",
      date: "Januari 2023",
      description:
        "Sertifikasi nasional kompetensi pengembangan web tingkat junior yang diterbitkan oleh BNSP.",
      credentialId: "TIK 1565 00100 2023",
      image: "/certificate/junior-web-dev.jpg",
      skills: ["Pengembangan Web", "PHP", "Laravel", "JavaScript"],
      expiryDate: "Januari 2026",
    },
    {
      id: "cert-2",
      title: "Certificate of Competence",
      issuer: "PT. Global Intermedia Nusantara",
      date: "Mei 2023",
      description:
        "Sertifikat kompetensi profesional yang diberikan oleh PT. Global Intermedia Nusantara.",
      credentialId: "NO. 422/0562",
      image: "/certificate/certificate-of-competence.jpg",
      skills: ["Pengembangan Web", "PHP", "Laravel", "JavaScript"],
    },
    {
      id: "cert-3",
      title: "TOEIC Listening and Reading",
      issuer: "PT Internasional Test Center-TOEIC Center Indonesia",
      date: "Agustus 2022",
      description:
        "Sertifikat TOEIC untuk kompetensi bahasa Inggris pada kemampuan listening dan reading.",
      credentialId: "0045453942",
      image: "/certificate/toeic.jpg",
      skills: ["Bahasa Inggris", "TOEIC"],
      expiryDate: "Agustus 2025",
    },
    {
      id: "cert-4",
      title: "Udemy - Java Android",
      issuer: "Udemy",
      date: "Agustus 2022",
      description: "Menyelesaikan kursus Java Android di Udemy.",
      credentialId: "UC-fb4eb8b8-6af3-407f-9121-315d135ef666",
      image: "/certificate/udemy_java-android.jpg",
      skills: ["Java", "Android"],
    },
    {
      id: "cert-5",
      title: "Udemy - Golang",
      issuer: "Udemy",
      date: "Februari 2025",
      description: "Menyelesaikan kursus Golang di Udemy.",
      credentialId: "UC-03a9ee15-ec75-46b4-8ea4-f2886ee312f5",
      image: "/certificate/udemy_golang.jpg",
      skills: ["Golang"],
    },
    {
      id: "cert-6",
      title: "Dicoding - Jaringan Komputer untuk Pemula",
      issuer: "Dicoding",
      date: "Juli 2023",
      description: "Pengantar dasar jaringan komputer dari Dicoding.",
      credentialId: "72ZD8R7E6ZYW",
      image: "/certificate/dicoding-jaringan-komputer-untuk-pemula.jpg",
      skills: ["Jaringan"],
    },
    {
      id: "cert-7",
      title: "Dicoding - Cloud Practitioner Essentials",
      issuer: "Dicoding",
      date: "Agustus 2023",
      description: "Dasar-dasar komputasi cloud dari Dicoding.",
      credentialId: "N9ZO61288XG5",
      image: "/certificate/dicoding_cloud-practitioner-essentials.jpg",
      skills: ["Cloud", "AWS"],
    },
    {
      id: "cert-8",
      title: "Dicoding - Dasar-dasar DevOps",
      issuer: "Dicoding",
      date: "Agustus 2023",
      description: "Pengantar DevOps dan praktik dasarnya dari Dicoding.",
      credentialId: "N9ZO6JLLYXG5",
      image: "/certificate/dicoding_dasar-dasar-devops.jpg",
      skills: ["DevOps"],
    },
    {
      id: "cert-9",
      title: "Dicoding - Dasar Manajemen Proyek",
      issuer: "Dicoding",
      date: "September 2023",
      description: "Dasar-dasar manajemen proyek TI dari Dicoding.",
      credentialId: "07Z689G4MXQR",
      image: "/certificate/dicoding_dasar-manajemen-proyek.jpg",
      skills: ["Manajemen Proyek"],
    },
    {
      id: "cert-10",
      title: "Dicoding - Dasar Pemrograman JavaScript",
      issuer: "Dicoding",
      date: "Maret 2023",
      description: "Fundamental pemrograman JavaScript dari Dicoding.",
      credentialId: "L4PQ6V887PO1",
      image: "/certificate/dicoding_dasar-pemrograman-javascript.jpg",
      skills: ["JavaScript"],
    },
    {
      id: "cert-11",
      title: "Dicoding - Dasar Pemrograman untuk Menjadi Pengembang Software",
      issuer: "Dicoding",
      date: "Oktober 2023",
      description: "Dasar pemrograman untuk menjadi pengembang software dari Dicoding.",
      credentialId: "EYX4YN9VJZDL",
      image: "/certificate/dicoding_dasar-pemrograman-untuk-menjadi-pengembang-software.jpg",
      skills: ["Pemrograman"],
    },
    {
      id: "cert-12",
      title: "Dicoding - Dasar SQL",
      issuer: "Dicoding",
      date: "Oktober 2023",
      description: "Dasar SQL untuk kebutuhan database dari Dicoding.",
      credentialId: "JLX1WQL2GP72",
      image: "/certificate/dicoding_dasar-sql.jpg",
      skills: ["SQL", "Database"],
    },
    {
      id: "cert-13",
      title: "Dicoding - Membuat Aplikasi Backend untuk Pemula",
      issuer: "Dicoding",
      date: "April 2023",
      description: "Pembelajaran membangun aplikasi backend tingkat pemula dari Dicoding.",
      credentialId: "N9ZO6JLLYXG5",
      image: "/certificate/dicoding_membuat-aplikasi-backend-pemula.jpg",
      skills: ["Backend", "Node.js"],
    },
    {
      id: "cert-14",
      title: "Sololearn - HTML",
      issuer: "Sololearn",
      date: "Agustus 2023",
      description: "Menyelesaikan kursus HTML di Sololearn.",
      credentialUrl: "CC-ETTW60WQ",
      image: "/certificate/sololean_html.png",
      skills: ["HTML"],
    },
    {
      id: "cert-15",
      title: "Sololearn - jQuery",
      issuer: "Sololearn",
      date: "Juni 2023",
      description: "Menyelesaikan kursus jQuery di Sololearn.",
      credentialUrl: "CT-S5ILW5ZT",
      image: "/certificate/sololearn_jquery.png",
      skills: ["jQuery"],
    },
    {
      id: "cert-16",
      title: "Sololearn - PHP",
      issuer: "Sololearn",
      date: "Mei 2022",
      description: "Menyelesaikan kursus PHP di Sololearn.",
      credentialUrl: "CT-MP2GXEUC",
      image: "/certificate/sololearn_php.png",
      skills: ["PHP"],
    },
    {
      id: "cert-17",
      title: "SQL Intermediate",
      issuer: "Sololearn",
      date: "April 2023",
      description: "Sertifikat SQL tingkat menengah dari Sololearn.",
      credentialUrl: "CC-QNMP3OC8",
      image: "/certificate/sololearn_sql-intermediate.png",
      skills: ["SQL"],
    },
  ],
  contact: {
    title: "tentang ide atau kebutuhan teknis Anda",
    description:
      "Saya siap berdiskusi untuk peran fullstack/backend, kolaborasi produk, atau proyek web yang membutuhkan struktur sistem kuat dan antarmuka yang jelas.",
    email: "alfiangadingsaputra@gmail.com",
    interests: [
      "Backend API",
      "Fullstack Web",
      "Laravel",
      "Go",
      "Next.js",
      "Database",
      "Deployment",
    ],
  },
};
