import { Github, Linkedin, Mail } from "lucide-react";
import { PortfolioData } from "@/types/portfolio";

export const PORTFOLIO_DATA: PortfolioData = {
  navigation: [
    { label: "About", href: "#about" },
    { label: "Experience", href: "#experience" },
    { label: "Projects", href: "#projects" },
    { label: "Education", href: "#education" },
    { label: "Achievements", href: "#achievements" },
    { label: "Certifications", href: "#certifications" },
    { label: "Contact", href: "#contact" },
  ],
  socials: [
    {
      icon: Github,
      href: "https://github.com/Alfian57",
      label: "GitHub",
    },
    {
      icon: Linkedin,
      href: "https://www.linkedin.com/in/alfian-gading-saputra/",
      label: "LinkedIn",
    },
    {
      icon: Mail,
      href: "mailto:alfiangadingsaputra@gmail.com",
      label: "Email",
    },
  ],
  hero: {
    greeting: "Hi, I'm",
    name: "Alfian Gading Saputra",
    tagline: "Fullstack Developer",
    description:
      "A Fullstack Developer who bridges the gap between logic and design. I build high-performance backends with Go & Laravel and interactive frontends with Next.js. My goal? To ship robust applications that are as secure as they are beautiful.",
    cta: {
      primary: "View My Work",
      secondary: "Get In Touch",
    },
  },
  about: {
    title: "About Me",
    description: [
      "I view software development as a craft, not just coding. My expertise lies in architecting secure, high-performance backends using Golang and Laravel, seamlessly integrated with dynamic Next.js frontends. I don't just build features; I design resilient system architectures that prioritize security, scalability, and clean code principles.",
      "My workflow is driven by precision and efficiency. Whether I'm optimizing database queries, configuring Docker environments on Linux, or refining a UI component, I enjoy the challenge of making complex systems feel simple. I thrive in bridging the gap between heavy backend logic and delightful user experiences.",
      "Beyond the syntax, I believe in building software that lasts. I strive to write self-documenting, maintainable code that future developers will appreciate, while delivering applications that are robust, secure, and ready to scale."
    ],
    skills: [
      "Golang",
      "Laravel",
      "Next.js",
      "TypeScript",
      "SQL",
      "Tailwind CSS",
      "Node.js",
      "Docker",
      "Git",
      "Linux",
    ],
  },
  experiences: [
    {
      id: "exp-1",
      title: "Backend Developer",
      company: "UTY Software House",
      location: "Daerah Istimewa Yogyakarta, Indonesia",
      period: "July 2025 - Present",
      description: [
        "Architecting scalable backend services using Laravel, focusing on clean code structure and secure API design.",
        "Designing efficient database schemas and optimizing SQL queries to handle complex data relationships.",
        "Collaborating with frontend teams to define API specifications and ensuring smooth data flow across the application.",
      ],
      technologies: ["PHP", "Laravel"],
      type: "Contract",
      images: [
        "/experience/USH-1.jpeg",
        "/experience/USH-2.jpeg",
      ],
    },
    
    {
      id: "exp-2",
      title: "Fullstack Developer",
      company: "Seven Inc Jogja",
      location: "Daerah Istimewa Yogyakarta, Indonesia",
      period: "June 2023 - September 2023",
      description: [
        "Built and customized content management solutions using WordPress and Laravel to meet specific client requirements.",
        "Managed Linux-based server environments, handling basic deployment and configuration tasks to ensure uptime.",
        "Optimized database queries and backend scripts to improve page load speeds and overall system performance.",
      ],
      technologies: ["PHP", "Laravel", "Wordpress", "Linux"],
      type: "Internship",
      images: [
        "/experience/Seven-Inc-1.jpg",
        "/experience/Seven-Inc-2.jpg",
      ],
    },
    {
      id: "exp-3",
      title: "Fullstack Developer",
      company: "PT. Integra Inovasi Indonesia",
      location: "Daerah Istimewa Yogyakarta, Indonesia",
      period: "June 2022 - December 2022",
      description: [
        "Developed and maintained web applications using Laravel, ensuring seamless integration between backend logic and frontend views.",
        "Collaborated on mobile application development using Java (Android), specifically handling RESTful API consumption and data synchronization.",
        "Participated in bug fixing and feature enhancements to improve application stability and user experience.",
      ],
      technologies: ["PHP", "Laravel", "Java", "Android"],
      type: "Internship",
      images: [
        "/experience/Integra-1.jpg",
      ],
    },
  ],
  projects: [
    {
      id: "proj-1",
      title: "E-Commerce Platform",
      description:
        "A full-featured e-commerce platform with real-time inventory, payment processing, and admin dashboard.",
      image: "🛍️",
      technologies: ["Next.js", "Stripe", "Prisma", "PostgreSQL"],
      tags: ["Web", "E-Commerce", "Full-stack"],
      images: [
        "https://images.unsplash.com/photo-1557821552-17105176677c?w=800&q=80",
        "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80",
        "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&q=80"
      ],
      link: "https://example.com",
      github: "https://github.com/yourusername/project",
      featured: true,
    },
    {
      id: "proj-2",
      title: "Task Management App",
      description:
        "Collaborative task management tool with real-time updates, drag-and-drop, and team features.",
      image: "📋",
      technologies: ["React", "Firebase", "Framer Motion", "Tailwind"],
      tags: ["Web", "Productivity", "Full-stack"],
      images: [
        "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800&q=80",
        "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&q=80"
      ],
      link: "https://example.com",
      github: "https://github.com/yourusername/project",
      featured: true,
    },
    {
      id: "proj-3",
      title: "Portfolio Builder",
      description: "No-code portfolio builder with customizable templates and themes.",
      image: "🎨",
      technologies: ["Next.js", "TypeScript", "Shadcn UI"],
      tags: ["Web", "Design", "Frontend"],
      images: [
        "https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&q=80"
      ],
      link: "https://example.com",
      featured: true,
    },
    {
      id: "proj-4",
      title: "Weather Dashboard",
      description: "Real-time weather dashboard with interactive maps and forecasts.",
      image: "🌤️",
      technologies: ["React", "OpenWeather API", "Chart.js"],
      tags: ["Web", "API", "Frontend"],
      images: [
        "https://images.unsplash.com/photo-1592210454359-9043f067919b?w=800&q=80",
        "https://images.unsplash.com/photo-1504608524841-42fe6f032b4b?w=800&q=80"
      ],
      link: "https://example.com",
    },
    {
      id: "proj-5",
      title: "Social Media Analytics",
      description: "Analytics dashboard for tracking social media metrics and engagement.",
      image: "📊",
      technologies: ["Next.js", "D3.js", "REST API"],
      tags: ["Web", "Analytics", "Full-stack"],
      images: [
        "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80"
      ],
      github: "https://github.com/yourusername/project",
    },
    {
      id: "proj-6",
      title: "Blogging Platform",
      description: "Modern blogging platform with markdown support and SEO optimization.",
      image: "✍️",
      technologies: ["Next.js", "MDX", "Contentlayer"],
      tags: ["Web", "Content", "Full-stack"],
      images: [
        "https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=800&q=80",
        "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=800&q=80"
      ],
      link: "https://example.com",
    },
    {
      id: "proj-7",
      title: "Real-time Chat App",
      description: "A scalable chat application with rooms, presence, and message history.",
      image: "💬",
      technologies: ["Next.js", "Socket.IO", "Redis"],
      tags: ["Web", "Realtime", "Full-stack"],
      images: [
        "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80",
        "https://images.unsplash.com/photo-1522202227194-2f0b6c8d2b73?w=800&q=80"
      ],
      link: "https://example.com",
      github: "https://github.com/yourusername/chat-app",
    },
    {
      id: "proj-8",
      title: "FinTech Dashboard",
      description: "Interactive dashboard for financial insights and transaction analytics.",
      image: "💹",
      technologies: ["Next.js", "D3.js", "PostgreSQL"],
      tags: ["Web", "Analytics", "Full-stack"],
      images: [
        "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800&q=80",
        "https://images.unsplash.com/photo-1526378727632-5d26b3b6b1d9?w=800&q=80"
      ],
      github: "https://github.com/yourusername/fintech-dashboard",
    },
    {
      id: "proj-9",
      title: "Mobile Workout Planner",
      description: "Cross-platform mobile app to plan workouts and track progress.",
      image: "🏋️",
      technologies: ["React Native", "Expo", "SQLite"],
      tags: ["Mobile", "Health", "Frontend"],
      images: [
        "https://images.unsplash.com/photo-1519861531928-0c0b5c9b3b1b?w=800&q=80"
      ],
      link: "https://example.com",
    },
    {
      id: "proj-10",
      title: "Image Recognition API",
      description: "REST API for image classification using a lightweight ML model.",
      image: "🧠",
      technologies: ["Go", "TensorFlow", "Docker"],
      tags: ["Backend", "AI", "API"],
      images: [
        "https://images.unsplash.com/photo-1518779578993-ec3579fee39f?w=800&q=80"
      ],
      github: "https://github.com/yourusername/image-recognition-api",
    },
    {
      id: "proj-11",
      title: "Open Source Design System",
      description: "A design system with accessible components and documentation.",
      image: "🎛️",
      technologies: ["React", "TypeScript", "Tailwind CSS"],
      tags: ["Web", "Design", "Frontend"],
      images: [
        "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&q=80"
      ],
      link: "https://example.com",
      github: "https://github.com/yourusername/design-system",
    },
    {
      id: "proj-12",
      title: "Event Booking Platform",
      description: "Platform to create, discover, and book local events with ticketing.",
      image: "🎟️",
      technologies: ["Next.js", "Stripe", "Prisma"],
      tags: ["Web", "E-Commerce", "Full-stack"],
      images: [
        "https://images.unsplash.com/photo-1504805572947-34fad45aed93?w=800&q=80",
        "https://images.unsplash.com/photo-1496307042754-b4aa456c4a2d?w=800&q=80"
      ],
      link: "https://example.com",
    },
  ],
  education: [
    {
      id: "edu-1",
      degree: "Bachelor of Computer Science",
      institution: "Universitas Teknologi Yogyakarta",
      location: "Daerah Istimewa Yogyakarta, Indonesia",
      period: "2023 - Present",
      description: 
        "Currently deepening knowledge in Data Structures, Algorithms, and System Architecture. Actively bridging the gap between academic theory and industry standards by applying software engineering principles in real-world projects via UTY Software House.",
    },
    {
      id: "edu-2",
      degree: "Software Engineering",
      institution: "SMK Negeri 1 Bantul",
      location: "Daerah Istimewa Yogyakarta, Indonesia",
      period: "2020 - 2023",
      description:
        "Built a strong foundation in web development fundamentals, Database Management, and Object-Oriented Programming (OOP). Gained practical experience in full-stack implementation through vocational training and industry internships.",
    },
  ],
  achievements: [
    {
      id: "ach-1",
      title: "2nd Place LKS ITSSB Provincial Level DIY",
      issuer: "Disdikpora DIY",
      date: "May 2022",
      description:
        "Secured 2nd place in the prestigious vocational competition for IT Software Solutions for Business (ITSSB) at the provincial level.",
      detailedDescription:
        "Developed a comprehensive software ecosystem under strict time constraints. The project included a Desktop Point of Sales (POS) application built with C# .NET for retail management and a sophisticated Android-based Cloud Storage application (similar to Google Drive) using Java, demonstrating strong file handling and API synchronization skills.",
      tags: ["C# .NET", "Java Android", "Desktop App", "System Integration"],
      images: [
        "/achivement/LKS-1.jpeg",
        "/achivement/LKS-2.jpeg",
        "/achivement/LKS-3.jpeg",
      ],
      link: "/achivement/LKS-Cert.jpg",
    },
    {
      id: "ach-2",
      title: "3rd Place LKS ITSSB National Level",
      issuer: "Ministry of Education and Culture Republic of Indonesia",
      date: "October 2022",
      description:
        "Achieved 3rd rank nationally, competing against top talents from 34 provinces in Indonesia in the IT Software Solutions for Business field.",
      detailedDescription:
        "Engineered a fully integrated business solution combining Desktop, Web, and Mobile modules. Proved expertise in C# .NET and Java by solving complex business logic problems and delivering a fault-tolerant system under high-pressure national competition standards.",
      tags: ["National Award", "C# .NET", "Java", "Fullstack Engineering"],
      images: [
        "/achivement/LKSN-1.jpeg",
        "/achivement/LKSN-2.jpeg",
        "/achivement/LKSN-3.jpeg",
      ],
      link: "/achivement/LKSN-Cert.jpg",
    },
    {
      id: "ach-3",
      title: "PKM-KC Funding Awardee (SINDIKAT)",
      issuer: "Kemdikbudristek",
      date: "August 2024",
      description:
        "Awarded research grant funding for 'SINDIKAT', an Innovative Creation (PKM-KC) project utilizing Deep Learning for security.",
      detailedDescription:
        "Served as the Lead Backend Developer for 'SINDIKAT: Sistem Multi Device Pendeteksi Tindakan Kriminal Menggunakan Deep Learning'. Responsible for architecting the RESTful APIs that process real-time alerts from AI detection models and managing the data flow between multi-device endpoints and the central dashboard.",
      tags: ["PKM-KC", "AI Integration", "Backend Architecture", "Deep Learning"],
      images: [],
      link: "/achivement/PKM-Cert.jpg",
    },
  ],
  certifications: [
    {
      id: "cert-1",
      title: "Junior Web Developer",
      issuer: "Badan Nasional Sertifikasi Profesi (BNSP)",
      date: "January 2023",
      description: "National certification for junior-level web development competency, issued by BNSP.",
      credentialId: "TIK 1565 00100 2023",
      image: "/certificate/junior-web-dev.jpg",
      skills: ["Web Development", "PHP", "Laravel", "JavaScript"],
      expiryDate: "January 2026",
    },
    {
      id: "cert-2",
      title: "Certificate of Competence",
      issuer: "PT. Global Intermedia Nusantara",
      date: "Mei 2023",
      description: "Professional competency certificate awarded by PT. Global Intermedia Nusantara.",
      credentialId: "NO. 422/0562",
      image: "/certificate/certificate-of-competence.jpg",
      skills: ["Web Development", "PHP", "Laravel", "JavaScript"],
    },
    {
      id: "cert-3",
      title: "TOEIC Listening and Reading",
      issuer: "PT Internasional Test Center-TOEIC Center Indonesia",
      date: "August 2022",
      description: "TOEIC certificate for English listening and reading proficiency.",
      credentialId: "0045453942",
      image: "/certificate/toeic.jpg",
      skills: ["English", "TOEIC"],
      expiryDate: "August 2025",
    },
    {
      id: "cert-4",
      title: "Udemy - Java Android",
      issuer: "Udemy",
      date: "August 2022",
      description: "Completed the Java Android course on Udemy.",
      credentialId: "UC-fb4eb8b8-6af3-407f-9121-315d135ef666",
      image: "/certificate/udemy_java-android.jpg",
      skills: ["Java", "Android"],
    },
    {
      id: "cert-5",
      title: "Udemy - Golang",
      issuer: "Udemy",
      date: "February 2025",
      description: "Completed the Golang course on Udemy.",
      credentialId: "UC-03a9ee15-ec75-46b4-8ea4-f2886ee312f5",
      image: "/certificate/udemy_golang.jpg",
      skills: ["Golang"],
    },
    {
      id: "cert-6",
      title: "Dicoding - Jaringan Komputer untuk Pemula",
      issuer: "Dicoding",
      date: "July 2023",
      description: "Introduction to basic computer networking from Dicoding.",
      credentialId: "72ZD8R7E6ZYW",
      image: "/certificate/dicoding-jaringan-komputer-untuk-pemula.jpg",
      skills: ["Networking"],
    },
    {
      id: "cert-7",
      title: "Dicoding - Cloud Practitioner Essentials",
      issuer: "Dicoding",
      date: "August 2023",
      description: "Fundamentals of cloud computing from Dicoding.",
      credentialId: "N9ZO61288XG5",
      image: "/certificate/dicoding_cloud-practitioner-essentials.jpg",
      skills: ["Cloud", "AWS"],
    },
    {
      id: "cert-8",
      title: "Dicoding - Dasar-dasar DevOps",
      issuer: "Dicoding",
      date: "August 2023",
      description: "Introduction to DevOps and its basic practices from Dicoding.",
      credentialId: "N9ZO6JLLYXG5",
      image: "/certificate/dicoding_dasar-dasar-devops.jpg",
      skills: ["DevOps"],
    },
    {
      id: "cert-9",
      title: "Dicoding - Dasar Manajemen Proyek",
      issuer: "Dicoding",
      date: "September 2023",
      description: "Fundamentals of IT project management from Dicoding.",
      credentialId: "07Z689G4MXQR",
      image: "/certificate/dicoding_dasar-manajemen-proyek.jpg",
      skills: ["Project Management"],
    },
    {
      id: "cert-10",
      title: "Dicoding - Dasar Pemrograman JavaScript",
      issuer: "Dicoding",
      date: "March 2023",
      description: "Fundamentals of JavaScript programming from Dicoding.",
      credentialId: "L4PQ6V887PO1",
      image: "/certificate/dicoding_dasar-pemrograman-javascript.jpg",
      skills: ["JavaScript"],
    },
    {
      id: "cert-11",
      title: "Dicoding - Dasar Pemrograman untuk Menjadi Pengembang Software",
      issuer: "Dicoding",
      date: "October 2023",
      description: "Basic programming for software development from Dicoding.",
      credentialId: "EYX4YN9VJZDL",
      image: "/certificate/dicoding_dasar-pemrograman-untuk-menjadi-pengembang-software.jpg",
      skills: ["Programming"],
    },
    {
      id: "cert-12",
      title: "Dicoding - Dasar SQL",
      issuer: "Dicoding",
      date: "October 2023",
      description: "Fundamentals of SQL for databases from Dicoding.",
      credentialId: "JLX1WQL2GP72",
      image: "/certificate/dicoding_dasar-sql.jpg",
      skills: ["SQL", "Database"],
    },
    {
      id: "cert-13",
      title: "Dicoding - Membuat Aplikasi Backend untuk Pemula",
      issuer: "Dicoding",
      date: "April 2023",
      description: "Building beginner-level backend applications from Dicoding.",
      credentialId: "N9ZO6JLLYXG5",
      image: "/certificate/dicoding_membuat-aplikasi-backend-pemula.jpg",
      skills: ["Backend", "Node.js"],
    },
    {
      id: "cert-14",
      title: "Sololearn - HTML",
      issuer: "Sololearn",
      date: "August 2023",
      description: "Completed the HTML course on Sololearn.",
      credentialUrl: "CC-ETTW60WQ",
      image: "/certificate/sololean_html.png",
      skills: ["HTML"],
    },
    {
      id: "cert-15",
      title: "Sololearn - jQuery",
      issuer: "Sololearn",
      date: "June 2023",
      description: "Completed the jQuery course on Sololearn.",
      credentialUrl: "CT-S5ILW5ZT",
      image: "/certificate/sololearn_jquery.png",
      skills: ["jQuery"],
    },
    {
      id: "cert-16",
      title: "Sololearn - PHP",
      issuer: "Sololearn",
      date: "May 2022",
      description: "Completed the PHP course on Sololearn.",
      credentialUrl: "CT-MP2GXEUC",
      image: "/certificate/sololearn_php.png",
      skills: ["PHP"],
    },
    {
      id: "cert-17",
      title: "SQL Intermediate",
      issuer: "Sololearn",
      date: "April 2023",
      description: "Intermediate-level SQL certificate from Sololearn.",
      credentialUrl: "CC-QNMP3OC8",
      image: "/certificate/sololearn_sql-intermediate.png",
      skills: ["SQL"],
    },
  ],
  contact: {
    title: "Let's Work Together",
    description:
      "I'm always open to discussing new projects, creative ideas, or opportunities to be part of your vision.",
    email: "alfiangadingsaputra@gmail.com",
  },
};
